In [3]:
import pandas as pd


data = pd.read_csv("zoo.csv")

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
animal_name    101 non-null object
hair           101 non-null int64
feathers       101 non-null int64
eggs           101 non-null int64
milk           101 non-null int64
airborne       101 non-null int64
aquatic        101 non-null int64
predator       101 non-null int64
toothed        101 non-null int64
backbone       101 non-null int64
breathes       101 non-null int64
venomous       101 non-null int64
fins           101 non-null int64
legs           101 non-null int64
tail           101 non-null int64
domestic       101 non-null int64
catsize        101 non-null int64
class_type     101 non-null int64
dtypes: int64(17), object(1)
memory usage: 14.3+ KB


In [9]:
import numpy as np
labels = data['class_type']
print(np.unique(labels.values))

#from matplotlib import pyplot as plot
#%matplotlib inline
#fig, ax = plot.subplots()
#(labels.value_counts()).plot(ax=ax, kind='bar')

[1 2 3 4 5 6 7]


In [6]:
data.head()
data.shape

(101, 18)

In [12]:
features=data.values[:,1:-1]
features
features.shape

(101, 16)

In [13]:
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import pairwise_distances

model = AgglomerativeClustering(n_clusters=7,
                                    linkage="average", affinity="cosine")

In [14]:
model.fit(features)

AgglomerativeClustering(affinity='cosine', compute_full_tree='auto',
                        connectivity=None, distance_threshold=None,
                        linkage='average', memory=None, n_clusters=7)

In [15]:
model.labels_

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 6, 0, 0, 0, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 4, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 5, 0, 0, 4, 3, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 3, 0], dtype=int64)

In [16]:
print(np.unique(model.labels_))


[0 1 2 3 4 5 6]


In [18]:
labels = labels -1
labels

0     -1
1     -1
2      2
3     -1
4     -1
      ..
96    -1
97     4
98    -1
99     5
100    0
Name: class_type, Length: 101, dtype: int64

In [35]:
from sklearn.metrics import mean_squared_error

In [36]:
score = mean_squared_error(labels,model.labels_)

In [37]:
abs_error = np.sqrt(score)
print(abs_error)

2.43733339111


In [2]:
cd D:\Darvin\python training

D:\Darvin\python training
